# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.18.0.dev7"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.providers.experimental.pyenv",
  "pants.backend.python.mixed_interpreter_constraints"
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]


[python]
enable_resolves = true
resolves = { python-default = "python-default.lock"}
interpreter_constraints = ["CPython>=3.7.0,<3.12"]
default_resolve = "python-default"


[python.resolves_to_interpreter_constraints]
python-default = ["CPython>=3.7.0,<3.12"]

